version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  relative-path-mode: wd

formatters:
  enable:
    - gofmt
    - golines
    - swaggo
  settings:
    golines:
      max-len: 140
      tab-len: 4

    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
linters:
  default: none
  enable:
    # --- Обязательные ---
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - mnd
    - whitespace

    # --- Баги ---
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errorlint
    - nilerr
    - rowserrcheck
    - sqlclosecheck
    - fatcontext

    # --- Качество кода ---
    - gocritic
    - goconst
    - gocyclo
    - unparam
    - dupl
    - prealloc
    - forbidigo

    # --- Безопасность ---
    - gosec

    # --- Стиль ---
    - misspell
    - revive
    - nlreturn
    - wsl_v5

  settings:
    forbidigo:
      analyze-types: true
      forbid:
        - pattern: '^fmt\.Print.*$'
          msg: Используй логгер с уровнем DEBUG или INFO
        - pattern: '^log\.Print.*$'
          msg: Используй логгер с уровнем DEBUG или INFO
        - pattern: '^log\.Fatal.*$'
          msg: Используй логгер с уровнем ERROR
        - pattern: '^time\.Sleep$'

    goconst:
      min-len: 2
      numbers: true

    gocyclo:
      min-complexity: 15

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - hugeParam

    gosec:
      excludes:
        - G404

    dupl:
      threshold: 150

    misspell:
      locale: US

    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: var-naming
        - name: receiver-naming
        - name: error-naming
        - name: error-return
        - name: exported
        - name: unexported-return
        - name: indent-error-flow

        - name: if-return
        - name: early-return
        - name: superfluous-else
        - name: empty-block
        - name: unreachable-code

        - name: redefines-builtin-id
        - name: modifies-parameter
        - name: confusing-naming

        - name: line-length-limit
          arguments: [140]

        - name: blank-imports
        - name: atomic

        - name: cognitive-complexity
          arguments: [30]
        - name: package-comments
          disable: true

  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives

    rules:
      - path: "_test\\.go"
        linters:
          - gosec
          - dupl
          - goconst

      - path: "_test\\.go"
        linters:
          - gocyclo

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
