// Package photo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package photo

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error  string `json:"error"`
	Status string `json:"status"`
}

// EvaluateSuccessResponse defines model for EvaluateSuccessResponse.
type EvaluateSuccessResponse struct {
	ID     *openapi_types.UUID `json:"id,omitempty"`
	Status string              `json:"status"`
}

// EvaluateUploadRequest defines model for EvaluateUploadRequest.
type EvaluateUploadRequest struct {
	// DisplayID ID дисплея
	DisplayID *int `json:"display_id,omitempty"`

	// Image Файл изображения (JPEG, PNG, GIF)
	Image openapi_types.File `json:"image"`

	// MethodID ID метода
	MethodID int `json:"method_id"`
}

// EvaluateMultipartRequestBody defines body for Evaluate for multipart/form-data ContentType.
type EvaluateMultipartRequestBody = EvaluateUploadRequest
