// Package photo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package photo

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	// ID Уникальный идентификатор фотографии
	ID openapi_types.UUID `json:"id"`
}

// UploadPhotoMultipartBody defines parameters for UploadPhoto.
type UploadPhotoMultipartBody struct {
	// Photo Файл фотографии
	Photo openapi_types.File `json:"photo"`
}

// UploadPhotoMultipartRequestBody defines body for UploadPhoto for multipart/form-data ContentType.
type UploadPhotoMultipartRequestBody UploadPhotoMultipartBody
