// Package photo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package photo

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Загрузка фотографии
	// (POST /api/v1/evaluate)
	Evaluate(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Evaluate operation middleware
func (siw *ServerInterfaceWrapper) Evaluate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Evaluate(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/evaluate", wrapper.Evaluate)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7yU32rcRhTGX0Wc9qIFNVrnTwm6a6lrXNriOvQqhDKWjq0JkmYyMzI1ZsGOcxEo1NCb",
	"XvWitA+gONlYibubVzjzRuWMdr3dPwmUltwIMTMa/b7vfOccQ6YqrWqsnYX0GGxWYCXC66Yxyuyi1aq2",
	"yAvaKI3GSQzbyNv84o40QgrWGVkfwDAG64Rr7JqtYQwGHzXSYA7p/dm5eHrVg3h2Xu09xMzxVZuHomyE",
	"w3tNlqG1b6eROT/3lamEgxSaRuYQ/2e0dyF9r0sl8l181KB1q0C5tLoURz/0YDnazEjtpKohhe0vInpB",
	"nT+lN3RFI3/OHvwoKl0ipLfvfBpDJWtZNRWkG9cEsnZ4gIYRZCUOcPVa+pNaekVXEXV0SRN65k+opZc0",
	"ojF1/jz66Kudza042vl2K462tr/8GOK5YXuyFuZonWUVukLlb9XxF438Y5rQC2r/qWLj5q13q1gyfP6X",
	"mbxV7/kbWe+rNcp/p5E/oQv2lK298ucRXVJLz/2JP6NLek1d5J/QJKA+Z1/8E+roVURdFFbfBK8uwkG6",
	"iHbF3p5033zHhkjHgmCnUE5FfdWje2gOZYbRZzvbEMMhGtuDbNwY3Biwa0pjLbSEFG6FpRi0cEVIRiK0",
	"TA43EpwGKWRH9RlakvXrtYSX1LLRa0T4n2eK/Rm9pjboHtOYz9BkoUBB7XLwOLSCf7idQ3qdbujLg9Z9",
	"rvIjRstU7bAOlFVTOqmFcQnn55NcODGfHfz2ocF9SOGDZD5ckulkSdb3z3AxEM40GBb6fg++3RwMljiE",
	"1qXMAnzy0LJl/xZiea4EjKUi/BHsGvmnNKZ2NVgtl/v2/8m2MHfXEf1GI7oIiR/7nzjETMQJnvhTprnz",
	"Xml+obE/84/9SRg0Y3/OHk38U+roGfsT+dNpd/KzDa1vm6riebOQ8cv+9GqbduGbpEBRugLS43ADGm47",
	"SO8vd83XKhNl1O9DDI0pIYXCOZ0mScl7hbIuvTu4O5h2IgwfDP8OAAD//0s0n8MIBwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
