// Package photo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package photo

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Загрузка фотографии
	// (POST /photos/upload)
	UploadPhoto(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// UploadPhoto operation middleware
func (siw *ServerInterfaceWrapper) UploadPhoto(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadPhoto(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/photos/upload", wrapper.UploadPhoto)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVXWsbRxT9K8O0j1uvnDQQ9q2B1Lg0RU0pfUj8sNKOrQnSznZmZDDBIMl5MKREtC99",
	"aSml/QGya8VryVL+wrn/qNzZ+KPSgl+KX0bDzNWdc8895+5r2Ta9wuQq904mr6Vrd1QvDdun1hrLm8Ka",
	"QlmvVThum0zxrz8olEyk81bne/Iwkj3lXLpXd3cYSat+7GurMpm8qDLcxO9EV/Gm9Uq1Pef6vuiaNHuu",
	"XGFyp9ZB6IzXTLm21YXXJpeJxF9YoMQME8zpJyzoLS4ESpxhigWNUNKb6ppGWNJA0BsseYt/aIBJuCxl",
	"JHeN7aVeJrLf15mM7qhFZzX4OUjnu6YG45+Y0gCnKGkocIY5jQXOMWEMdIRzzFDWAeNCRDj9wGc4DYE4",
	"Fc/TVkv7Z98yUO27jKLZMd6IikHxnbL7uq3EF81tGcl9ZV0FZHOjsdFgpk2h8rTQMpEPw1Eki9R3Aslx",
	"wZlc3A+pQhOM8zVF/XpdwHtMMKVRTQn0bq2EOY1DMKb08+1arok5u2olprigY14FljgJ/z8JuWYoN17m",
	"+ANLnHGnaYD3KHGKCb2jEQ1pXGEZ4JIbT28T8VXz6VYkmt9sRWJr+8tI/KBaTc7xGyaY0RAlh96SUHjt",
	"HJecPBGbDfHsycbLXAbqbMocbGcy+SjZQL6sNKKcf2Kyg8o0uVd54K7X73pdpNbHrLTPstSnN8ZbV3ro",
	"QQ3nf2OCC8zvVHFL56k9uFPH1TP1Ur6J87avwkHlywDwQePBSoVpUXR1OzATv3IM93Z5n1q1KxP5SXwz",
	"eOKPUydesX14fa3uVWGNRVBUiQWNaYQJS2lVJXTEWv+80fjfoFbTsQ7h75hixpKjAe9odDWK2OeMdEnD",
	"gGbz4T2gudbJEHOUdMzQcCmYGNY4HWOJiwrOo3si58O6WTHFZWW2W2ZlVI/upWW/YEFHNAoNWwQdjXlU",
	"HaPECX8xmL1qbvM6Ce5x/V6PnfWf+XdeRdd70qd77tprTu4EJE5ZnsoyebFq8a9NO+2K6l5Gsm+7MpEd",
	"74skjrt81zHOJ48bjxtxWuh4f1Me7hz+GwAA//+Wd5/C0AcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
