// Package photo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package photo

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Загрузка фотографии
	// (POST /api/v1/evaluate)
	Evaluate(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Evaluate operation middleware
func (siw *ServerInterfaceWrapper) Evaluate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Evaluate(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/evaluate", wrapper.Evaluate)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7yU32rcRhTGX0Wc9qIFNVrnTwm6a6lrXNriOvQqhDKWjq0JkmYyMzI1ZsGOcxEo1NCb",
	"XvWitA+gONlYibubVzjzRuWMdr3ZPwmUlt4sw8zs6Pd95zvnGDJVaVVj7Sykx2CzAisRlpvGKLOLVqva",
	"Im9oozQaJzEcIx/zwh1phBSsM7I+gGEM1gnX2DVHwxgMPmqkwRzS+7N78fSpB/Hsvtp7iJnjpzYPRdkI",
	"h/eaLENr300jc/7dV6YSDlJoGplD/K/R3of0vS6VyHfxUYPWrQLl0upSHP3Qg+VoMyO1k6qGFLa/iOgF",
	"df6U3tAVjfw5e/CjqHSJkN6+82kMlaxl1VSQblwTyNrhARpGkJU4wNVn6U9q6RVdRdTRJU3omT+hll7S",
	"iMbU+fPoo692NrfiaOfbrTja2v7yY4jnhu3JWpijdZZV6AqVv1PHXzTyj2lCL6h9W8XGzVvvV7Fk+Pwr",
	"8dvWzbSuFoIfkPW+WmPD7zTyJ3TBBrPPV/48oktq6bk/8Wd0Sa+pi/wTmgTu52ySf0IdvYqoi8Lum2Dc",
	"RbhIF9Gu2NuT7pvv2B3pWB3sFMqpqI9AdA/Nocww+mxnG2I4RGN7kI0bgxsDtlBprIWWkMKtsBWDFq4I",
	"MUmElsnhRoLTVIUgqT5QS7J+vZbwklp2fY0I//NMsT+j19QG3WMa8x2aLFQrqF1OISdY8Ae3c0ivow59",
	"rdC6z1V+xGiZqh3WgbJqSie1MC7hMH2SCyfmg4RXHxrchxQ+SOaTJpmOmWR9Mw0X0+FMg2Gjb/7g283B",
	"YIlDaF3KLMAnDy1b9k8hlodMwFgqwh/BrpF/SmNqV4PVcrlv/5dsC0N4HdFvNKKLkPix/4lDzESc4Ik/",
	"ZZo7/yvNLzT2Z/6xPwlTZ+zP2aOJf0odPWN/In867U7+bcMcsE1V8fBZyPhlf3u1Tbvwn6RAUboC0uPw",
	"AhpuO0jvL3fN1yoTZdSfQwyNKSGFwjmdJknJZ4WyLr07uDuYdiIMHwz/DgAA//8MKVrRFQcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
