// Package websocket provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package websocket

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error  string `json:"error"`
	Status string `json:"status"`
}

// ConnectWebSocketParams defines parameters for ConnectWebSocket.
type ConnectWebSocketParams struct {
	// ChannelID Уникальный ID канала (UUID), используемый для связи HTTP запроса и WebSocket
	ChannelID openapi_types.UUID `form:"channel_id" json:"channel_id"`
}
