// Package websocket provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package websocket

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// WebSocket подключение
	// (GET /ws)
	ConnectWebSocket(c *gin.Context, params ConnectWebSocketParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ConnectWebSocket operation middleware
func (siw *ServerInterfaceWrapper) ConnectWebSocket(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ConnectWebSocketParams

	// ------------- Required query parameter "channel_id" -------------

	if paramValue := c.Query("channel_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument channel_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "channel_id", c.Request.URL.Query(), &params.ChannelID, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConnectWebSocket(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/ws", wrapper.ConnectWebSocket)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/2xTzU4bMRB+FWvaA0grNlF7QHtDpVIj9RAVUA8IVcvGENONbWxvEEKR8lOph6LyBD31",
	"BZaIFVtCllcYv1FlJyHh55J4PeOZ75vvmwtIREcKTrnREF2ATtq0E/vjR6WE+kK1FFxTdyGVkFQZRn2Y",
	"urA7mHNJIQJtFOPH0AtAm9hk+pVQLwBFTzOmaAui/UVeMC91ECzyxeEJTQz03APGj4Qr1aI6UUwaJjhE",
	"sNVsELzBib0idmQHdog5TrHCMd5hSc40wQes8AbvcGJ/259Y4BRLewUBGGZS16PZFkaQPZmKuEV2qOqy",
	"hJKtZgMC6FKlZ23qG7WNmqMkJOWxZBDBO38VgIxN23MMz/zfMTUvYeLfR2w5jnGCJY4xx8IOyVd6uCOS",
	"79QQO8AKC7zBEqczoFgsyHkaEztaUiC2jwXe2hFO7KWrbYeON8EKr20fc7zGyg79GOwPf6w2wBNQsUPV",
	"aEEEHwTnNDGPGDwfFXeooUpDtP+Sh4d1h7nrilP7C/+RxjbxN47bBHOytrfX2F4PCJZ2MMd96YEWeO8f",
	"LAQb4Nhe4S2W5NPubpPgLeb4YPtY2QHmBEuyiou5/qcZVecQAI87TrukHXNO02+sBauOMiqjwdzBTosj",
	"oTqxgQiyzGc+d+OBezyzt5ewXqu/lHDnjJmkzfgxaSphRCJSTdZWxHvqvomTad055n2t5oolghvKvTVi",
	"KVOWeBHCE+2KX6yAfavoEUTwJlzuYzhfxvDpJvq1eKbPHyxwjIXtz7VZnSlZ8xK5rxLvXVJAnDHswI78",
	"7xDHTiU7JMvBrvtt1VmnE6tziGDJ+LXNwmKGSlPVfd1Bn0USp2QWhwAylUIEbWNkFIapi7WFNtFmbbMW",
	"xpKF3Tr0Dnr/AwAA//9dnpZxnQQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
